site_name: xz's Leetcode
theme:
  name: material
  features:
    - content.math
nav:
  - Home: index.md
  - Array: array.md
  - String: string.md
  - LinkedList: linkedlist.md
  - DFSBFS: dfsbfs.md
  - Graph: graph.md