site_name: xz's Leetcode
theme:
  name: material
nav:
  - Home: index.md
  - Array: array.md
  - String: string.md
  - LinkedList: linkedlist.md
  - DFS: dfs.md
  - BFS: bfs.md
  - Graph: graph.md
  - Greedy: greedy.md
  - Simulation: simulation.md
  - Math: math.md
  - DP: dp.md
  - Tree: tree.md